GET {{host}}/cockroach-demo/api/car/dealer/003ac07f-2f56-501e-beb5-3ffda0fc0048

###

GET {{host}}/cockroach-demo/api/car/statistics/Opel

###

POST {{host}}/cockroach-demo/api/car/
Content-Type: application/json

{
    "name": "Test",
    "vin": "ABCDEF",
    "brand": "Steyr",
    "dealer": "00013709-567e-5b0f-ac62-4c672d59dd14"
}

###