GET {{host}}/cockroach-demo/api/car/dealer/2de59e8b-123d-4c5e-8716-bca1113e9a53

###

POST {{host}}/cockroach-demo/api/car/
Content-Type: application/json

{
    "name": "Test",
    "vin": "ABCDEF",
    "dealer": "43cefe39-a88f-4d64-8f90-157d5bbda0e0"
}

###